prompt on defrag

diff --git a/scripts/bootcache b/scripts/bootcache
--- a/scripts/bootcache
+++ b/scripts/bootcache
@@ -199,6 +199,7 @@ function do_defrag()
     fi
 
     # do poor man's defrag
+    echo -n "running poor man's defrag for task '$TASK' ..."
     $FILECACHE --load "$DEFRAG_ROOT" \
                 --defrag "$DEFRAG_HABITAT"
 
@@ -206,7 +207,7 @@ function do_defrag()
     local retval=$?
     rm -fr "$DEFRAG_ROOT.old"
     mv "$DEFRAG_ROOT" "$DEFRAG_ROOT.old"
-    [ $retval -eq 0 ] || return 1
+    [ $retval -eq 0 ] || { echo 'failed'; return 1; }
 
     # update the moved fs metadata
     # it will include old metadata from the deleted inodes
@@ -215,6 +216,8 @@ function do_defrag()
                 --delete-if 'not f.blockdev?' \
                 --union "$PRELOAD_ROOT/bdev" \
                 --dump "$PRELOAD_ROOT"
+
+    echo 'done'
 }
 
 function do_clear()
